steps:
  - label: "Triggering Pipelines (Pull Request)"
    if: "build.pull_request.base_branch == 'main'"
    agents:
      queue: "juliagpu"
    plugins:
      - monebag/monorepo-diff#v2.5.9:
          diff: ".buildkite/scripts/diff.sh $BUILDKITE_COMMIT"
          interpolation: false
          watch:
            - path:
                - "src/"
                - "ext/"
                - "test/"
                - "Project.toml"
                - ".buildkite/"
              config:
                command: "buildkite-agent pipeline upload .buildkite/testing.yml"
                agents:
                  queue: "juliagpu"

  - label: "Triggering Pipelines (Main Branch / Tag)"
    if: build.branch == "main" || build.tag != null
    agents:
      queue: "juliagpu"
    command: "buildkite-agent pipeline upload .buildkite/testing.yml"

  - label: "Documentation"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=docs -e '
        println("--- :julia: Instantiating project")
        using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()
        println("+++ :julia: Building documentation")
        include("docs/make.jl")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip docs\]/ && !build.pull_request.draft
    timeout_in_minutes: 120

env:
  # SECRET_DOCUMENTER_KEY: 
