name: documentation
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  docs:
    if: github.ref == 'refs/heads/main'
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-buildpkg@v1

      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          julia --project=docs -e '
          println("--- :julia: Instantiating project")
          using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()
          println("+++ :julia: Building documentation")
          include("docs/make.jl")'